version: '3'
services: 
    #mssql docker
 healthcare-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment: 
        - ACCEPT_EULA=Y
        - SA_PASSOWRD=test
        - MSSQL_PID=Developer
    ports: 
        - 1401:1433
    networks:
        - healthcare020-net
    
 healthcare020-api:
    restart: unless-stopped
    build:
       context: .
    environment: 
        - ConnectionStrings:Healthcare020=Server=healthcare-sql,1433;Database=Healthcare020;User=sa;Password=test;ConnectRetryCount=0
    ports: 
        - 5200:80
    networks:
        - healthcare020-net
    links:
        - healthcare-sql
    depends_on: 
        - healthcare-sql
networks:
    healthcare020-net:
        driver: bridge